const indianEquity =  [
  {
    scripCode: "532540",
    symbol: "TCS",
    name: "Tata Consultancy Services",
    industry: "IT Services & Consulting",
    exchange: "BSE",
    industryCode: "50010",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "500209",
    symbol: "INFY",
    name: "Infosys",
    industry: "IT Services & Consulting",
    exchange: "BSE",
    industryCode: "50010",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "500325",
    symbol: "RELIANCE",
    name: "Reliance Industries Limited",
    industry: "Conglomerate",
    exchange: "BSE",
    industryCode: "50015",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "500010",
    symbol: "HDFC",
    name: "HDFC",
    industry: "Finance (Housing)",
    exchange: "BSE",
    industryCode: "50025",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "500875",
    symbol: "ITC",
    name: "ITC Limited",
    industry: "Cigarettes & FMCG",
    exchange: "BSE",
    industryCode: "50020",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "500696",
    symbol: "HINDUNILVR",
    name: "Hindustan Unilever Limited",
    industry: "FMCG",
    exchange: "BSE",
    industryCode: "50020",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "500034",
    symbol: "BAJFINANCE",
    name: "Bajaj Finance",
    industry: "Finance (NBFC)",
    exchange: "BSE",
    industryCode: "50025",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "500112",
    symbol: "SBIN",
    name: "State Bank of India",
    industry: "Banking - Public",
    exchange: "BSE",
    industryCode: "50025",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "500510",
    symbol: "L&T",
    name: "Larsen & Toubro",
    industry: "Engineering & Construction",
    exchange: "BSE",
    industryCode: "50030",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "532281",
    symbol: "HCLTECH",
    name: "HCL Technologies",
    industry: "IT Services & Consulting",
    exchange: "BSE",
    industryCode: "50010",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "532500",
    symbol: "MARUTI",
    name: "Maruti Suzuki",
    industry: "Automobile",
    exchange: "BSE",
    industryCode: "50035",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "500520",
    symbol: "M&M",
    name: "Mahindra & Mahindra",
    industry: "Automobile",
    exchange: "BSE",
    industryCode: "50035",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "532538",
    symbol: "ULTRACEMCO",
    name: "UltraTech Cement",
    industry: "Cement",
    exchange: "BSE",
    industryCode: "50040",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "500790",
    symbol: "NESTLEIND",
    name: "Nestlé India",
    industry: "FMCG",
    exchange: "BSE",
    industryCode: "50020",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "532898",
    symbol: "POWERGRID",
    name: "Power Grid Corporation of India",
    industry: "Power generation/Distribution",
    exchange: "BSE",
    industryCode: "50015",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "532555",
    symbol: "NTPC",
    name: "NTPC",
    industry: "Power generation/Distribution",
    exchange: "BSE",
    industryCode: "50015",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "500312",
    symbol: "ONGC",
    name: "Oil and Natural Gas Corporation",
    industry: "Oil exploration and Production",
    exchange: "BSE",
    industryCode: "50015",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "",
    symbol: "ADANIPORTS",
    name: "Adani Ports",
    industry: "Infrastructure",
    exchange: "BSE",
    industryCode: "50030",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "",
    symbol: "BPCL",
    name: "Bharat Petroleum",
    industry: "	Energy - Oil & Gas",
    exchange: "BSE",
    industryCode: "50015",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "",
    symbol: "HEROMOTOCO",
    name: "Hero MotoCorp",
    industry: "Automobile",
    exchange: "BSE",
    industryCode: "50035",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "",
    symbol: "HINDALCO",
    name: "Hindalco Industries",
    industry: "Metals",
    exchange: "BSE",
    industryCode: "50045",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "",
    symbol: "IOC",
    name: "Indian Oil Corporation",
    industry: "Energy - Oil & Gas",
    exchange: "BSE",
    industryCode: "50015",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "",
    symbol: "JSWSTEEL",
    name: "JSW Steel",
    industry: "Metals",
    exchange: "BSE",
    industryCode: "50045",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "",
    symbol: "SHREECEM",
    name: "Shree Cements",
    industry: "Cement",
    exchange: "BSE",
    industryCode: "50040",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "",
    symbol: "TATACONSUM",
    name: "Tata Consumer Products",
    industry: "Consumer Goods",
    exchange: "BSE",
    industryCode: "50020",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "",
    symbol: "UPL",
    name: "United Phosphorus Limited",
    industry: "Chemicals",
    exchange: "BSE",
    industryCode: "50050",
    locale: "IN",
    currency: "INR",
  },
  {
    scripCode: "",
    symbol: "TATASTEEL",
    name: "Tata Steel",
    industry: "Metals",
    exchange: "BSE",
    industryCode: "50045",
    locale: "IN",
    currency: "INR",
  }
];

const usEquity =  [
  {
    symbol: "INFY",
    name: "Infosys Adr",
    industry: "IT Services & Consulting",
    exchange: "NYSE",
    industryCode: "50010",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "IBN",
    name: "ICICI Bank adr",
    industry: "Banking - (Private)",
    exchange: "NYSE",
    industryCode: "50025",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "HDB",
    name: "HDFC Bank adr",
    industry: "Banking and Financial services",
    exchange: "NYSE",
    industryCode: "50025",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "TTM",
    name: "Tata Motors adr",
    industry: "Automobiles",
    exchange: "NYSE",
    industryCode: "50035",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "VEDL",
    name: "Vedanta Ltd adr",
    industry: "Mining",
    exchange: "NYSE",
    industryCode: "",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "WIT",
    name: "Wipro adr",
    industry: "IT Services & Consulting",
    exchange: "NYSE",
    industryCode: "50010",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "WNS",
    name: "WNS Holdings adr",
    industry: "Business process management",
    exchange: "NYSE",
    industryCode: "",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "RDY",
    name: "Dr. Reddy’s Labs ADR",
    industry: "Pharmaceutical",
    exchange: "NYSE",
    industryCode: "50070",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "MMYT",
    name: "MakeMyTrip adr",
    industry: "Travel & Leisure",
    exchange: "NASDAQ",
    industryCode: "",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "SIFY",
    name: "Sify adr",
    industry: "Information and communications technology",
    exchange: "NASDAQ",
    industryCode: "50010",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "YTRA",
    name: "Yatra Online adr",
    industry: "Travel & Leisure",
    exchange: "NASDAQ",
    industryCode: "50055",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "AZRE",
    name: "Azure Power Global adr",
    industry: "Utilities—Renewable",
    exchange: "NYSE",
    industryCode: "50015",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "VDTH",
    name: "Videocon D2H Limited adr",
    industry: "Satellite TV",
    exchange: "NASDAQ",
    industryCode: "50060",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "AAPL",
    name: "Apple Inc",
    industry: "Information technology",
    exchange: "	NASDAQ",
    industryCode: "50010",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "BA",
    name: "Boeing",
    industry: "Aerospace and defense",
    exchange: "NASDAQ",
    industryCode: "",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "KO",
    name: "The Coca-Cola Company",
    industry: "Food industry",
    exchange: "NYSE",
    industryCode: "50090",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "CSCO",
    name: "Cisco Systems",
    industry: "Information technology",
    exchange: "NASDAQ",
    industryCode: "50010",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "AXP",
    name: "American Express",
    industry: "Financial services",
    exchange: "NYSE",
    industryCode: "50025",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "GS",
    name: "Goldman Sachs",
    industry: "Financial services",
    exchange: "NYSE",
    industryCode: "50025",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "IBM",
    name: "IBM",
    industry: "Information technology",
    exchange: "NYSE",
    industryCode: "50010",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "INTC",
    name: "Intel",
    industry: "Information technology",
    exchange: "NASDAQ",
    industryCode: "50010",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase",
    industry: "Financial services",
    exchange: "NYSE",
    industryCode: "50025",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "MCD",
    name: "McDonald's",
    industry: "Food industry",
    exchange: "NYSE",
    industryCode: "50090",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "MRK",
    name: "Merck & Co",
    industry: "Pharmaceutical industry",
    exchange: "NYSE",
    industryCode: "50070",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    industry: "Pharmaceutical industry",
    exchange: "NYSE",
    industryCode: "50070",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    industry: "Information technology",
    exchange: "NASDAQ",
    industryCode: "50010",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "NKE",
    name: "Nike, Inc.",
    industry: "	Apparel",
    exchange: "NYSE",
    industryCode: "50075",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "V",
    name: "Visa Inc",
    industry: "Financial services",
    exchange: "NYSE",
    industryCode: "50025",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "WMT",
    name: "Walmart",
    industry: "Retailing",
    exchange: "NYSE",
    industryCode: "50080",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "WBA",
    name: "Walgreens Boots Alliance",
    industry: "Retailing",
    exchange: "NASDAQ",
    industryCode: "50080",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "DIS",
    name: "The Walt Disney Company",
    industry: "Broadcasting and entertainment",
    exchange: "NYSE",
    industryCode: "",  
    locale: "US",
    currency: "USD",
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc",
    industry: "Automobiles",
    exchange: "NASDAQ",
    industryCode: "50035",  
    locale: "US",
    currency: "USD",
  }
];


export default {
  indianEquity,
  usEquity
};